name: fight_club
description: A simple RPG character creator and idle game.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0
  gap: ^2.0.0
  hive: ^2.0.4
  meta: ^1.7.0
  path_provider: ^2.0.5
  synchronized: ^3.0.0
  theme:
    path: packages/theme
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
