name: theme
description: Fight club theme.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_icon: ^0.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Thin.ttf
          weight: 100
        - asset: fonts/RobotoMono-ThinItalic.ttf
          weight: 100
        - asset: fonts/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: fonts/RobotoMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: fonts/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: fonts/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: fonts/RobotoMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: fonts/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
